# Generated by Django 4.1.1 on 2022-10-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('total_price', models.FloatField()),
                ('actual_price', models.FloatField()),
                ('delivery_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media/% Y/% m/% d/')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_category.suncategory')),
            ],
        ),
    ]
