# Generated by Django 4.1.1 on 2022-11-22 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('content_number', models.IntegerField(default=0, unique=True)),
                ('content_title', models.CharField(max_length=50)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='course/content/content_image/')),
                ('doc_url', models.FileField(blank=True, null=True, upload_to='course/content/content_document/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_description', models.CharField(default='description', max_length=100)),
                ('video_url', models.FileField(default=' ', null=True, upload_to='course/content/content_video/')),
                ('chapter_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chapters.chapter')),
                ('content_creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('content_title',),
            },
        ),
    ]
