# Generated by Django 3.2.16 on 2022-12-10 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('create_date', models.DateField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('content_number', models.IntegerField(default=0)),
                ('content_title', models.CharField(max_length=50)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='course/content/content_image/')),
                ('doc_url', models.FileField(blank=True, null=True, upload_to='course/content/content_document/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('content_description', models.CharField(default='description', max_length=100)),
                ('video_url', models.FileField(default=' ', upload_to='course/content/content_video/')),
                ('content_type', models.IntegerField(choices=[(100, 'content'), (101, 'question')], default=100)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chapters.chapter')),
                ('content_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('content_title',),
            },
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('content_number', 'chapter_id'), name='content should be only in single chapter'),
        ),
    ]
