# Generated by Django 3.2.16 on 2022-12-20 03:13

import applications.content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('create_date', models.DateField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('content_number', models.IntegerField(default=0)),
                ('content_title', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('content_description', models.CharField(default='description', max_length=100)),
                ('url', models.FileField(blank=True, null=True, upload_to=applications.content.models.Content.uploadFiles)),
                ('youtube_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('content_type', models.IntegerField(choices=[(100, 'Video'), (101, 'Image'), (102, 'Document'), (103, 'Question'), (104, 'Youtube Video')], default=100)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents_in_chapter', to='chapters.chapter')),
                ('content_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('content_title',),
            },
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('content_number', 'chapter_id'), name='content should be only in single chapter'),
        ),
    ]
