# Generated by Django 4.1.1 on 2022-10-26 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('category_image', models.ImageField(upload_to='category/')),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='takesContentId', to='category.category')),
            ],
        ),
    ]
