# Generated by Django 3.2.16 on 2022-12-20 03:12

import applications.category.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('category_image', models.FileField(blank=True, upload_to=applications.category.models.Category.uploadFiles)),
            ],
            options={
                'ordering': ('category_name', 'description'),
            },
        ),
    ]
