# Generated by Django 4.1.1 on 2022-11-22 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('chapter_name', models.CharField(max_length=50)),
                ('Chapter_title', models.CharField(max_length=50)),
                ('chapter_number', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'ordering': ('chapter_name', 'Chapter_title'),
            },
        ),
    ]
