# Generated by Django 3.2.16 on 2022-12-10 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('create_date', models.DateField(auto_now=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('chapter_name', models.CharField(max_length=50)),
                ('chapter_title', models.CharField(max_length=50)),
                ('chapter_number', models.IntegerField(default=0)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_id', to='course.course')),
            ],
            options={
                'ordering': ('chapter_name', 'chapter_title'),
            },
        ),
    ]
