# Generated by Django 4.1.1 on 2022-11-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_course_level_course_course_type_and_more'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('chapter_name', 'chapter_title')},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='Chapter_title',
            new_name='chapter_title',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course_id', 'chapter_number')},
        ),
    ]
