# Generated by Django 4.1.1 on 2022-11-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_course_level_course_course_type_and_more'),
        ('chapters', '0002_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
