# Generated by Django 4.1.1 on 2022-11-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_course_level_course_course_type_and_more'),
        ('chapters', '0003_alter_chapter_chapter_number_alter_chapter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(default='da457fba-9ae7-4a19-9c73-04bf78f16788', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
