# Generated by Django 4.1.1 on 2022-11-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_course_level_course_course_type_and_more'),
        ('chapters', '0007_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course_id', 'chapter_title')},
        ),
    ]
