# Generated by Django 4.1.1 on 2022-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_alter_chapter_chapter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
