# Generated by Django 4.1.1 on 2022-11-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_alter_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
