# Generated by Django 4.1.1 on 2022-11-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_options'),
        ('chapters', '0012_chapter_create_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course_id', 'chapter_title'), ('course_id', 'chapter_name'), ('course_id', 'chapter_number')},
        ),
    ]
