# Generated by Django 4.1.1 on 2022-12-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0013_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='create_date',
            field=models.DateField(),
        ),
    ]
