# Generated by Django 4.1.1 on 2022-12-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0014_alter_chapter_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='create_dated',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
