# Generated by Django 4.1.1 on 2022-12-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0015_chapter_create_dated_alter_chapter_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='create_dated',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='create_date',
            field=models.DateField(),
        ),
    ]
