# Generated by Django 4.1.1 on 2022-10-26 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
