# Generated by Django 3.2.16 on 2022-12-10 08:40

import applications.course.validations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course/course_image/<django.db.models.fields.CharField>')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_description', models.CharField(default='description', max_length=100)),
                ('course_video', models.FileField(default=' ', null=True, upload_to='course/course_video/')),
                ('course_type', models.IntegerField(choices=[(100, 'free'), (101, 'premium'), (102, 'sponsord')], default=100)),
                ('course_level', models.IntegerField(choices=[(100, 'biginner'), (101, 'intermediate'), (102, 'advanced')], default=100)),
                ('assisitant_instructor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant', to=settings.AUTH_USER_MODEL)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
            options={
                'ordering': ('course_name',),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(default=0.0, validators=[applications.course.validations.Validations.validate_price])),
                ('instructor_price', models.FloatField(validators=[applications.course.validations.Validations.validate_price])),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(default='review note', max_length=200)),
                ('rating', models.IntegerField(choices=[(100, 'excellent'), (101, 'very good'), (102, 'good'), (103, 'not bad'), (104, 'bad')])),
                ('review_date', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_review', to='course.course')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollement',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('enroll_start_date', models.DateField(auto_now=True)),
                ('enroll_end_date', models.DateField()),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enroll', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_enroll', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Cart',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(choices=[(100, 'ordered'), (101, 'enrolled')])),
                ('course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_carts', to='course.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_price', to='course.courseprice'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
