# Generated by Django 4.1.1 on 2022-11-06 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assisitant_instructor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.CharField(default='description', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='course_price_id',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(default=' ', null=True, upload_to='course/course_video/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course/course_image/'),
        ),
    ]
